### ISSUE TITLE
Getting an error with WSDL submission

### ISSUE THREAD

**Issue by crpsalazar** [ElofssonLab/TOPCONS2#10]
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\xml\sax\expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts\topcons2_wsdl.py", line 191, in <module>
    sys.exit(main(g_params))
  File "scripts\topcons2_wsdl.py", line 120, in main
    myclient = Client(wsdl_url, cache=None)
  File "C:\ProgramData\Anaconda3\lib\site-packages\suds\client.py", line 115, in __init__
    self.wsdl = reader.open(url)
  File "C:\ProgramData\Anaconda3\lib\site-packages\suds\reader.py", line 150, in open
    d = self.fn(url, self.options)
  File "C:\ProgramData\Anaconda3\lib\site-packages\suds\wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "C:\ProgramData\Anaconda3\lib\site-packages\suds\reader.py", line 74, in open
    d = self.download(url)
  File "C:\ProgramData\Anaconda3\lib\site-packages\suds\reader.py", line 100, in download
    return sax.parse(string=content)
  File "C:\ProgramData\Anaconda3\lib\site-packages\suds\sax\parser.py", line 133, in parse
    sax.parse(source)
  File "C:\ProgramData\Anaconda3\lib\xml\sax\expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "C:\ProgramData\Anaconda3\lib\xml\sax\xmlreader.py", line 127, in parse
    self.close()
  File "C:\ProgramData\Anaconda3\lib\xml\sax\expatreader.py", line 240, in close
    self.feed("", isFinal = 1)
  File "C:\ProgramData\Anaconda3\lib\xml\sax\expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "C:\ProgramData\Anaconda3\lib\xml\sax\handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: no element found
```

**Comment by Jmonee** [comment]
I get the same error

**Comment by nanjiangshu** [comment]
Hi @crpsalazar and @Jmonee, 

Thanks for pointing out the problem. The WSDL API is not very robust for the current version. We are thinking replacing it with another API for batch mode. At the moment, you can submit your query through web API for up to 50000 sequences in one submission. 

Best,
Nanjiang
