### ISSUE TITLE
unable to use WSDL API getting error

### ISSUE THREAD

**Issue by james-workig** [ElofssonLab/TOPCONS2#9]
pip install suds
using python2
python topcons2_wsdl.py -m submit -seq seq.fa -jobname test

Traceback (most recent call last):
  File "topcons2_wsdl.py", line 191, in <module>
    sys.exit(main(g_params))
  File "topcons2_wsdl.py", line 120, in main
    myclient = Client(wsdl_url, cache=None)
  File "/home/james/.local/lib/python2.7/site-packages/suds/client.py", line 112, in __init__
    self.wsdl = reader.open(url)
  File "/home/james/.local/lib/python2.7/site-packages/suds/reader.py", line 152, in open
    d = self.fn(url, self.options)
  File "/home/james/.local/lib/python2.7/site-packages/suds/wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "/home/james/.local/lib/python2.7/site-packages/suds/reader.py", line 79, in open
    d = self.download(url)
  File "/home/james/.local/lib/python2.7/site-packages/suds/reader.py", line 101, in download
    return sax.parse(string=content)
  File "/home/james/.local/lib/python2.7/site-packages/suds/sax/parser.py", line 136, in parse
    sax.parse(source)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 125, in parse
    self.close()
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 243, in close
    self.feed("", isFinal = 1)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 224, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: no element found

**Comment by nanjiangshu** [comment]
Hi @james-workig, 

Thanks for your interest in TOPCONS. The WSDL API is not working at the moment for some platforms after system updating. We are looking for solutions. 

Best,

Nanjiang
